---
#- host: host1
#  gather_facts: False
#  remote_user: vagrant
#  vars:
#    port:8080
#  tasks:
#    - name: INtsll httpd package
#      yum: name=httpd stage=latest
#      sudo: yes


#---
- hosts: host1
  vars:
    http_port: 80
    max_clients: 200
  remote_user: vagrant
  tasks:
  - name: ensure apache is at the latest version
    yum: name=httpd state=latest
    sudo: yes
  #- name: write the apache config file
    #template: src=/srv/httpd.j2 dest=/etc/httpd.conf
    notify:
    - restart apache
  - name: ensure apache is running (and enable it at boot)
    service: name=httpd state=started enabled=yes
  handlers:
    - name: restart apache
      service: name=httpd state=restarted
      sudo: yes





