# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
 config.vm.define "web" do | web |
   web.vm.box = "centos/6"
   web.vm.hostname = "web"
   web.vm.network "private_network" , ip: "192.168.33.20"
   web.vm.network "forwarded_port" , guest: 80 , host: 8081
   web.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.name = "16.04-web01"
     vb.memory = "512"
   end
   end
   config.vm.define "db" do | db |
   db.vm.box = "centos/6"
   db.vm.hostname = "db"
   db.vm.network "private_network" , ip: "192.168.33.30"
   db.vm.provider "virtualbox" do |vb|
     vb.gui = false
     vb.name = "16.04-DB01"
     vb.memory = "512"
   end
   end
end




