VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
 config.vm.box = "centos/7"
 config.vm.network :private_network , ip: "192.168.33.10"
 config.vm.provision "ansible" do |ansible|
   #ansible.inventry_path = "hosts"
   ansible.playbook  =  "playbooks/example1.yml"
   ansible.verbose = "-vv"
   ansible.sudo = true
   ansible.limit = 'all'
 end
end





